# This is a basic workflow to help you get started with Actions

name: first workflow
on: workflow_dipatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      -name:print-greeting
      run: echo "hello"
      -name:print-greeting1
      run: echo "hello1"
