name: PR Synchronize Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        run: echo "asd"
