name: testProject
on: workflow_dispatch
jobs:
  first_job:
    needs: second_job
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        run: echo "new code is pushed"
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        run: echo "new code is pushed"
